import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
const p=path.dirname(fileURLToPath(import.meta.url));
const sharp=(await import(new URL('../../backend/node_modules/sharp/dist/index.mjs',import.meta.url))).default;
const voice=JSON.parse(await fs.readFile(path.join(p,'voice-meta.json'),'utf8'));
const capture=JSON.parse(await fs.readFile(path.join(p,'capture-meta.json'),'utf8'));
const captures=Object.fromEntries(capture.captures.map(c=>[c.id,c]));
await fs.mkdir(path.join(p,'assets/crops'),{recursive:true});await fs.mkdir(path.join(p,'compositions'),{recursive:true});
await fs.copyFile(path.join(p,'../process-guide-tour/assets/gsap.min.js'),path.join(p,'assets/gsap.min.js'));
await fs.copyFile(path.join(p,'../process-guide-tour/assets/inter-regular.ttf'),path.join(p,'assets/inter-regular.ttf'));
await fs.copyFile(path.join(p,'../process-guide-tour/assets/inter-medium.ttf'),path.join(p,'assets/inter-medium.ttf'));
await fs.copyFile(path.join(p,'../process-guide-tour/assets/INTER-LICENSE.txt'),path.join(p,'assets/INTER-LICENSE.txt'));
for(const l of voice.lines){const out=path.join(p,`assets/voice/${l.id}.wav`);execFileSync('ffmpeg',['-v','error','-y','-i',path.join(p,`assets/voice/${l.id}.mp3`),'-af','atempo=1.10','-ar','48000','-ac','1',out]);l.duration_s=Number(execFileSync('ffprobe',['-v','error','-show_entries','format=duration','-of','default=noprint_wrappers=1:nokey=1',out],{encoding:'utf8'}).trim());}
const padding=(90-voice.lines.reduce((a,l)=>a+l.duration_s,0))/voice.lines.length;if(padding<.2)throw Error('Narration too long');
let cursor=0;for(const l of voice.lines){l.start_s=cursor;l.end_s=cursor+l.duration_s+padding;l.voice_start_s=cursor+.12;l.voice_end_s=l.voice_start_s+l.duration_s;cursor=l.end_s;}
const crops={overview:[200,120,1200,660],source:[200,560,1200,310],guide:[205,405,1180,235],wishes:[500,320,600,530],resize:[180,70,1420,850],'resize-guidance':[325,735,860,245],steps:[1200,75,400,530],principles:[1200,75,400,470],manual:[1200,300,400,345],chat:[1175,630,420,335],guardian:[1200,75,400,420],readiness:[1200,205,400,435],review:[1200,130,400,330],exception:[1200,130,400,390],report:[290,35,1020,625],export:[300,275,920,310],account:[745,260,475,590],save:[370,535,850,295],saved:[370,60,860,610]};
const copy={overview:['Your process, in focus','A short guide to running, checking, and saving a session.'],source:['Choose your view','Upload footage, connect a camera, or share a screen.'],guide:['Add your instructions','Text or sample guides give the session its reference steps. Video-only steps remain provisional.'],wishes:['Tell the guide your wishes','Choose the focus, explanation style, and language you need.'],resize:['Make room for your work','Drag a divider to resize the source and guidance panels.'],'resize-guidance':['Resize your guidance','Use the corner grip to change width and height. Guardian messages have their own grips.'],steps:['Follow the workflow','Read the action, completion criteria, and visible evidence.'],principles:['Understand the purpose','Principles stay alongside the steps. Keep them in view as you work.'],manual:['Confirm with care','An operator confirmation is labeled separately from an AI observation.'],chat:['Ask when you need help','Type a question, use Listen, or enable spoken answers. Microphone access begins with your action.'],guardian:['Stay aware of the scene','Guardian collects ongoing observations. Pause guidance to inspect the source.'],readiness:['Prepare the run','Record the job context and check the preparation items yourself.'],review:['Keep the evidence','Bookmark the current frame so another reviewer can inspect the same moment.'],exception:['Flag what needs review','Raise an exception for uncertainty, a blocker, or a follow-up.'],report:['Bring the session together','The report combines workflow evidence, preparation, and review decisions.'],export:['Take the report with you','Prepare a PDF, export offline HTML, or share the file. Review its contents before sharing.'],account:['Keep a private record','Create an account or sign in on this deployment.'],save:['Save the current result','Keep this run in your local training workspace.'],saved:['Return to your results','Review saved evidence later. Accounts stay on this deployment; the simulator is planned and inactive.']};
const variants={resize:['resize','resize-guidance'],steps:['steps','principles'],review:['review','exception'],account:['account','save']};
const scenes=[];
for(const l of voice.lines){const ids=variants[l.id]||[l.id];for(let j=0;j<ids.length;j++){const id=ids[j],c=captures[id];let [x,y,w,h]=crops[id];if(id==='guide'){const top=Math.min(...c.highlights.map(z=>z.y));y=Math.max(0,Math.floor(top-80));h=260;}if(id==='source'){const top=Math.min(...c.highlights.map(z=>z.y));y=Math.max(0,Math.floor(top-70));h=290;}x=Math.max(0,Math.floor(x));y=Math.max(0,Math.floor(y));w=Math.min(1600-x,Math.floor(w));h=Math.min(1000-y,Math.floor(h));await sharp(path.join(p,c.src)).extract({left:x*2,top:y*2,width:w*2,height:h*2}).jpeg({quality:94,chromaSubsampling:'4:4:4'}).toFile(path.join(p,`assets/crops/${id}.jpg`));const start=l.start_s+(l.end_s-l.start_s)*j/ids.length,duration=(l.end_s-l.start_s)/ids.length;scenes.push({id,start,duration,crop:{x,y,w,h},highlights:c.highlights,title:copy[id][0],note:copy[id][1],voice_id:l.id});}}
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const common=`@font-face{font-family:TourInter;src:url('assets/inter-regular.ttf');font-weight:400}@font-face{font-family:TourInter;src:url('assets/inter-medium.ttf');font-weight:700}*{box-sizing:border-box}.tour-meta{position:absolute;left:60px;top:138px;color:#63c9ba;font-size:20px;font-weight:700;letter-spacing:.08em}.tour-copy{position:absolute;left:60px;top:188px;width:385px}.tour-title{font-size:55px;font-weight:700;line-height:1.09;letter-spacing:-.035em;margin:0 0 28px;color:#f4f8fa}.tour-note{font-size:26px;line-height:1.45;color:#c4d1d6;margin:0}.tour-view{position:absolute;left:510px;top:134px;width:1350px;height:730px;background:#eaf1f3;border:2px solid #344c59;border-radius:20px;overflow:hidden;box-shadow:0 18px 40px #05131b}.tour-camera{position:absolute;inset:0;transform-origin:50% 50%}.tour-screen{position:absolute;left:0;top:0;width:100%;height:100%;object-fit:contain}.tour-image-space{position:absolute;transform-origin:0 0}.tour-proof{position:absolute;border:5px solid transparent;border-radius:10px;--od-progress:0;--od-seam-overlap:.5deg;background:conic-gradient(from -90deg,#24b8a0 0deg calc(var(--od-progress)*3.6deg),transparent calc(var(--od-progress)*3.6deg + var(--od-seam-overlap)) 360deg);background-clip:border-box;background-origin:border-box;mask:linear-gradient(#f4f8fa 0 0) padding-box,linear-gradient(#f4f8fa 0 0) border-box;mask-composite:exclude;pointer-events:none}.tour-caption{position:absolute;left:60px;right:60px;top:913px;bottom:auto;margin:0;min-height:86px;padding:15px 25px;display:flex;align-items:center;justify-content:center;text-align:center;font-size:33px;line-height:1.3;color:#f4f8fa;background:#071d29;border-radius:14px}.tour-context{position:absolute;left:60px;top:811px;font-size:18px;color:#89a3af;letter-spacing:.03em}`;
for(let n=0;n<scenes.length;n++){const s=scenes[n],id=`tour-${s.id}`,scale=Math.min(1350/s.crop.w,730/s.crop.h),ix=(1350-s.crop.w*scale)/2,iy=(730-s.crop.h*scale)/2;const highlights=s.highlights.filter(h=>h.x+h.width>s.crop.x&&h.y+h.height>s.crop.y&&h.x<s.crop.x+s.crop.w&&h.y<s.crop.y+s.crop.h).map((h,k)=>{let hx=(h.x-s.crop.x)*scale+ix-6,hy=(h.y-s.crop.y)*scale+iy-6,hw=Math.max(24,h.width*scale+12),hh=h.height*scale+12;hx=Math.max(5,hx);hy=Math.max(5,hy);hw=Math.min(hw,1340-hx);hh=Math.min(hh,720-hy);return `<div id="${id}-proof-${k}" class="tour-proof" data-layout-ignore style="left:${hx}px;top:${hy}px;width:${hw}px;height:${hh}px"></div>`}).join('');
const line=voice.lines.find(l=>l.id===s.voice_id);const captionStart=Math.max(0,line.voice_start_s-s.start);const captionEnd=Math.min(s.duration,line.voice_end_s-s.start);const localCaption=`<p id="${id}-caption" class="clip tour-caption" data-start="${captionStart}" data-duration="${captionEnd-captionStart}" data-track-index="2" data-layout-allow-caption-zone>${esc(line.text)}</p>`;
const html=`<!doctype html><html><head><meta charset="utf-8"></head><body><template><style>${common}#${id}{position:absolute;inset:0;overflow:hidden;font-family:TourInter,sans-serif}</style><div id="${id}" data-composition-id="${id}" data-width="1920" data-height="1080" data-duration="${s.duration}"><div class="tour-meta">${String(n+1).padStart(2,'0')} · ${esc(s.id==='overview'?'START HERE':'HOW TO USE IT')}</div><div class="tour-copy"><h1 class="tour-title">${esc(s.title)}</h1><p class="tour-note">${esc(s.note)}</p></div><div class="tour-view"><div id="${id}-camera" class="tour-camera" data-layout-allow-overflow><img id="${id}-image" class="tour-screen" src="assets/crops/${s.id}.jpg" alt="Actual Process Guide ${s.id} screen"/>${highlights}</div></div><div class="tour-context">ACTUAL APP · SORTING EXAMPLE</div>${localCaption}</div><script>(()=>{const tl=gsap.timeline({paused:true});tl.fromTo('#${id} .tour-copy',{x:-12,opacity:0},{x:0,opacity:1,duration:.34,ease:'power2.out'},0);tl.fromTo('#${id} .tour-meta',{opacity:0},{opacity:1,duration:.2,ease:'power1.out'},0);tl.fromTo('#${id}-camera',{scale:1},{scale:1.015,duration:${Math.max(.1,s.duration-.2)},ease:'none'},.15);document.querySelectorAll('#${id} .tour-proof').forEach((el,k)=>{const at=.55+k*Math.min(1.1,${s.duration}/5);tl.fromTo(el,{'--od-progress':0,opacity:1},{'--od-progress':100,opacity:1,duration:.7,ease:'power2.out'},at);});window.__timelines['${id}']=tl;})();</script></template></body></html>`;await fs.writeFile(path.join(p,`compositions/${s.id}.html`),html);await fs.writeFile(path.join(p,`compositions/${s.id}.motion.json`),JSON.stringify({duration:s.duration,assertions:[{kind:'appearsBy',selector:`#${id} .tour-title`,bySec:.5},{kind:'staysInFrame',selector:`#${id} .tour-copy`}]},null,2));}
const clipHosts=scenes.map(s=>`<div class="clip" id="slot-${s.id}" data-composition-id="tour-${s.id}" data-composition-src="compositions/${s.id}.html" data-start="${s.start}" data-duration="${s.duration}" data-track-index="1" data-width="1920" data-height="1080"></div>`).join('\n');
const audio=voice.lines.map(l=>`<audio id="voice-${l.id}" src="assets/voice/${l.id}.wav" data-start="${l.voice_start_s}" data-duration="${l.duration_s}" data-track-index="3" data-volume="1"></audio>`).join('\n');
const captions=voice.lines.map(l=>`<div id="caption-${l.id}" class="clip caption-clip" data-start="${l.voice_start_s}" data-duration="${l.duration_s}" data-track-index="2"><p class="caption" data-layout-allow-caption-zone>${esc(l.text)}</p></div>`).join('\n');
const index=`<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Process Guide — narrated walkthrough</title><script src="assets/gsap.min.js"></script><style>@font-face{font-family:TourInter;src:url('assets/inter-regular.ttf');font-weight:400}@font-face{font-family:TourInter;src:url('assets/inter-medium.ttf');font-weight:700}*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden}#walkthrough{position:relative;width:100%;height:100%;background:#0c2432;color:#f4f8fa;font-family:TourInter,sans-serif}.clip{position:absolute;inset:0}.head{position:absolute;left:60px;right:60px;top:40px;height:44px;display:flex;align-items:center;justify-content:space-between}.brand{font-size:30px;font-weight:700;letter-spacing:-.025em}.edition{font-size:20px;color:#b0c3cc;letter-spacing:.055em}.rule{position:absolute;left:60px;right:60px;top:105px;height:2px;background:#344c59}.caption-clip{z-index:10}.caption{position:absolute;left:60px;right:60px;top:913px;margin:0;min-height:86px;padding:15px 25px;display:flex;align-items:center;justify-content:center;text-align:center;font-size:33px;line-height:1.3;color:#f4f8fa;background:#071d29;border-radius:14px}.progress-track{position:absolute;left:60px;right:60px;bottom:44px;height:5px;background:#344c59}.progress{height:5px;width:100%;background:#63c9ba;transform-origin:0 50%}</style></head><body><div id="walkthrough" data-composition-id="walkthrough" data-width="1920" data-height="1080" data-duration="90" data-fps="30"><div class="head"><div class="brand">Process Guide</div><div class="edition">A 90-SECOND WALKTHROUGH</div></div><div class="rule"></div>${clipHosts}${audio}<div class="progress-track"><div id="progress" class="progress" data-layout-ignore></div></div></div><script>const tl=gsap.timeline({paused:true});tl.fromTo('#progress',{scaleX:0},{scaleX:1,duration:90,ease:'none'},0);window.__timelines['walkthrough']=tl;</script></body></html>`;
await fs.writeFile(path.join(p,'index.html'),index);
const chapterGroups=[['start','Start and choose a source',['overview','source']],['setup','Instructions and wishes',['guide','wishes']],['workflow','Workspace, steps and confirmation',['resize','steps','manual']],['guidance','Questions and Guardian',['chat','guardian']],['readiness','Readiness',['readiness']],['review','Evidence and exceptions',['review']],['report','Reports, PDF and sharing',['report','export']],['account','Private account and saved results',['account','saved']]];
// Chapter seeks target the first encoded30fps frame of each scene. Voice and visual timing stay unrounded.
const chapterFrameTime=t=>Math.min(90,Math.ceil(t*30-1e-9)/30);
const metadata={title:'Process Guide: 90-second narrated tour',duration_s:90,language:'en',captions_burned_in:true,chapter_frame_rate:30,chapters:chapterGroups.map(([id,title,ids])=>{const ls=voice.lines.filter(l=>ids.includes(l.id));return{id,title,start_s:chapterFrameTime(ls[0].start_s),end_s:chapterFrameTime(ls.at(-1).end_s),text:ls.map(l=>l.text).join(' ')}}),transcript:voice.lines.map(l=>({start_s:l.voice_start_s,end_s:l.voice_end_s,text:l.text})),notes:'AI-generated narration. Screens are captured from the local app with deterministic document extraction; visual detection accuracy is not being benchmarked.'};
await fs.writeFile(path.join(p,'process-guide-walkthrough.json'),JSON.stringify(metadata,null,2));
const fmt=t=>{const ms=Math.round(t*1000);return`${String(Math.floor(ms/3600000)).padStart(2,'0')}:${String(Math.floor(ms/60000)%60).padStart(2,'0')}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}.${String(ms%1000).padStart(3,'0')}`};
await fs.writeFile(path.join(p,'process-guide-walkthrough.vtt'),'WEBVTT\n\n'+metadata.transcript.map((l,i)=>`${i+1}\n${fmt(l.start_s)} --> ${fmt(l.end_s)}\n${l.text}\n`).join('\n'));
await fs.writeFile(path.join(p,'index.motion.json'),JSON.stringify({duration:90,assertions:[{kind:'keepsMoving',withinSelector:'#progress',maxStaticSec:1},{kind:'staysInFrame',selector:'.head'}]},null,2));
await fs.writeFile(path.join(p,'timeline-plan.json'),JSON.stringify({duration:90,padding,voice:voice.lines,scenes},null,2));
await fs.writeFile(path.join(p,'STORYBOARD.md'),'# Instructional walkthrough\n\nA measured, steady tour: orient → prepare → follow → verify → save. Every button highlight is mapped from browser bounding boxes. Motion uses `coordinate-target-zoom` framing and the installed `outline-draw` primitive. Actual screens remain the focal layer; instructional copy stays in the left rail.\n\n'+scenes.map((s,i)=>`## Frame ${i+1}\n\nstatus: animated\nsrc: compositions/${s.id}.html\nstart: ${s.start.toFixed(3)}\nduration: ${s.duration.toFixed(3)}\nmotion: coordinate-target-zoom, outline-draw\n\n${s.title}. ${s.note}\n`).join('\n'));
await fs.writeFile(path.join(p,'design.md'),'# Process Guide walkthrough design\n\nConcept: a patient instructor points to real controls while the app remains readable.\n\nPalette: navy #0c2432; white #f4f8fa; muted #c4d1d6; teal #63c9ba; highlight #24b8a0; border #344c59; deep #05131b and #071d29; panel #eaf1f3; secondary #89a3af and #b0c3cc.\n\nTypography: locally embedded Inter, named TourInter, 400 body and 700 title. Single-family choice deliberately follows the actual product UI. Title55px, body26px, caption33px, labels18–20px.\n\nLayout: 60px edge anchors; narrative rail385px; actual screenshot frame1350×730;14–20px corners; restrained drop shadow.\n\nMotion: seek-safe slow1.015× camera move, exact-target clockwise outline draw, steady progress bar. Screens cut at authored boundaries. No generated UI, stock imagery, ornamental effects, or music masking speech.\n');
await fs.writeFile(path.join(p,'script.txt'),voice.lines.map(l=>l.text).join('\n\n')+'\n');
console.log(JSON.stringify({duration:cursor,voice_duration:voice.lines.reduce((a,l)=>a+l.duration_s,0),padding,scenes:scenes.length,chapters:metadata.chapters.map(c=>({title:c.title,start:c.start_s,end:c.end_s}))},null,2));
