import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
const project=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(project,'../..');
const load=(name:string)=>import(pathToFileURL(path.join(root,name)).href);
const {createApp}=await load('backend/src/app.ts');
const {GuidanceEngine}=await load('backend/src/pipeline/guidance.ts');
const {AccountStore}=await load('backend/src/account/store.ts');
const {chromium,expect}=await load('frontend/node_modules/@playwright/test/index.mjs');
const doc=await fs.readFile(path.join(root,'evaluation/assets/Parts_Sorting.txt'),'utf8');
const rows=doc.split(/(?=Step \d+:)/).filter(s=>s.startsWith('Step')).map(s=>({step:s.split('\n')[0].replace(/Step \d+: /,''),actions:s.match(/Actions: (.*)/)?.[1]||'',criteria:s.match(/Criteria: (.*)/)?.[1]||''}));
let fixtureCalls=0;
const engine=new GuidanceEngine(async(input:any)=>{fixtureCalls++;if(input.prompt.startsWith('Extract the provided'))return JSON.stringify({title:'Parts Sorting',steps:rows,principles:[doc.match(/Principles: (.*)/)?.[1]||'']});if(!input.json)return 'Inspect the visible contents of both bins before confirming a step.';return JSON.stringify({summary:'Instructional fixture: inspect the visible contents.',guidance:'Inspect the visible contents of both bins before confirming a step.',status:'watch',steps:[]});});
const accounts=new AccountStore({file:':memory:'});
const app=await createApp({engine,accountStore:accounts});
await app.listen({host:'127.0.0.1',port:8105});
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1600,height:1000},deviceScaleFactor:2,colorScheme:'light'});
await context.addInitScript(()=>localStorage.setItem('process-guide-theme','light'));
const page=await context.newPage();page.setDefaultTimeout(12000);
const errors:string[]=[];page.on('pageerror',(e:any)=>errors.push(e.message));
const captures:any[]=[];
await fs.mkdir(path.join(project,'assets/screens'),{recursive:true});
async function shot(id:string,targets:any[],region?:any){await page.waitForTimeout(400);const highlights=[];for(const target of targets){await expect(target).toBeVisible();const box=await target.boundingBox();if(!box)throw Error(`Missing target in ${id}`);highlights.push({label:await target.getAttribute('aria-label')||await target.innerText(),...box});}const crop=region?await region.boundingBox():{x:0,y:0,width:1600,height:1000};if(!crop)throw Error(`No crop ${id}`);const entry={id,src:`assets/screens/${id}.png`,viewport:{width:1600,height:1000,deviceScaleFactor:2},crop,highlights};await page.screenshot({path:path.join(project,entry.src)});captures.push(entry);console.log(`Captured ${id}`);}
async function tool(name:string){const tab=page.getByRole('tab',{name,exact:true});if(await tab.isVisible())await tab.click();else{await page.getByRole('button',{name:'More guidance tools'}).click();await page.getByRole('menuitem',{name,exact:true}).click();}}
try{
 await page.goto('http://127.0.0.1:8105');
 await shot('overview',[page.getByRole('link',{name:'Set up your session'})],page.locator('.intro-hero'));
 const source=page.getByRole('region',{name:'Choose a source'});await page.getByRole('button',{name:/Upload a video/}).scrollIntoViewIfNeeded();await page.evaluate(()=>window.scrollBy(0,240));
 await shot('source',[page.getByRole('button',{name:/Upload a video/}),page.getByRole('button',{name:/Use your camera/}),page.getByRole('button',{name:/Share a screen/})],page.locator('.intro-setup'));
 await page.getByTestId('intro-video-input').setInputFiles(path.join(root,'evaluation/assets/parts-sorting.mp4'));
 await page.getByRole('button',{name:'Upload guidance',exact:true}).scrollIntoViewIfNeeded();
 await shot('guide',[page.getByRole('button',{name:'Upload guidance',exact:true}),page.getByRole('combobox',{name:'Choose a sample guidance document'})],page.locator('.intro-setup'));
 await page.getByTestId('intro-document-input').setInputFiles(path.join(root,'evaluation/assets/Parts_Sorting.txt'));
 await expect(page.getByText('Parts_Sorting.txt · 4 steps extracted')).toBeVisible();
 await page.getByRole('button',{name:'Guidance goals',exact:true}).click();
 await page.getByLabel('Your wishes for this session').fill('Explain the principle behind each action. Keep guidance brief and practical.');
 await shot('wishes',[page.getByLabel('Your wishes for this session'),page.getByRole('button',{name:'Save goals',exact:true})],page.getByRole('dialog'));
 await page.getByRole('button',{name:'Save goals',exact:true}).click();
 await page.getByRole('button',{name:'Open workspace',exact:true}).click();
 await expect.poll(()=>page.locator('video').first().evaluate((v:HTMLVideoElement)=>v.readyState)).toBeGreaterThanOrEqual(2);
 const pause=page.getByRole('button',{name:'Pause guidance',exact:true});if(await pause.isVisible())await pause.click();
 await page.locator('video').first().evaluate((v:HTMLVideoElement)=>{v.pause();v.currentTime=4;});
 await shot('resize',[page.getByRole('separator').nth(1)],page.locator('.responsive-workspace'));
 const grips=[page.getByRole('button',{name:'Resize guidance area',exact:true})];const guardianGrip=page.getByRole('button',{name:'Resize Guardian message',exact:true});if(await guardianGrip.isVisible())grips.push(guardianGrip);await shot('resize-guidance',grips,page.locator('.workspace-video'));
 await tool('Steps');
 const article=page.getByTestId('step-S1');const trigger=article.getByRole('button').first();if((await trigger.getAttribute('aria-expanded'))==='false')await trigger.click();
 const confirm=page.getByRole('button',{name:'Confirm Inspect loose parts manually',exact:true});await confirm.scrollIntoViewIfNeeded();
 await shot('steps',[page.getByRole('tab',{name:'Steps',exact:true}),confirm],page.locator('.workspace-guidance'));
 await tool('Principles');await shot('principles',[page.getByRole('tab',{name:'Principles',exact:true})],page.locator('.workspace-guidance'));
 await tool('Steps');await confirm.scrollIntoViewIfNeeded();await confirm.click();
 await expect(page.getByRole('button',{name:'Reset Inspect loose parts manually',exact:true})).toBeVisible();
 await shot('manual',[page.getByRole('button',{name:'Reset Inspect loose parts manually',exact:true})],page.locator('.workspace-guidance'));
 await page.getByRole('button',{name:'Open chat',exact:true}).click();
 await page.getByRole('textbox',{name:'Message',exact:true}).fill('What evidence should I check before confirming the sorting step?');
 await shot('chat',[page.getByRole('textbox',{name:'Message',exact:true}),page.locator('.chat-panel').getByRole('button',{name:'Listen',exact:true}),page.getByRole('button',{name:'Voice answers',exact:true})],page.locator('.chat-panel'));
 await page.getByRole('button',{name:'Close chat',exact:true}).click();
 await tool('Guardian');await shot('guardian',[page.getByRole('tab',{name:'Guardian',exact:true})],page.locator('.workspace-guidance'));
 await tool('Readiness');
 await page.getByLabel('Work order',{exact:true}).fill('WO-1024');await page.getByLabel('Asset / workstation').fill('Parts sorting station');await page.getByLabel('Operator name').fill('Alex');
 await shot('readiness',[page.getByRole('button',{name:'Save job context',exact:true})],page.locator('.workspace-guidance'));
 await page.getByRole('button',{name:'Save job context',exact:true}).click();
 await tool('Review');await page.getByLabel('Evidence bookmark note').fill('Inspect both bins before the final confirmation.');
 await shot('review',[page.getByRole('button',{name:'Save frame',exact:true}),page.getByRole('button',{name:/^Exceptions/})],page.locator('.workspace-guidance'));
 await page.getByRole('button',{name:'Save frame',exact:true}).click();await page.getByRole('button',{name:/^Exceptions/}).click();await page.getByLabel('New exception title').fill('Final bin contents need review');
 await shot('exception',[page.getByRole('button',{name:'Raise exception',exact:true})],page.locator('.workspace-guidance'));
 await page.getByRole('button',{name:'Raise exception',exact:true}).click();
 await page.getByRole('button',{name:'Open analysis report',exact:true}).click();
 await shot('report',[page.getByRole('button',{name:'Prepare PDF',exact:true})],page.getByRole('dialog'));
 await page.getByRole('button',{name:'Prepare PDF',exact:true}).click();await expect(page.getByRole('button',{name:'Download PDF',exact:true})).toBeVisible({timeout:30000});
 console.log((await page.getByRole('dialog').getByRole('button').allTextContents()).join(' | '));
 await shot('export',[page.getByRole('button',{name:'Download PDF',exact:true}),page.getByRole('button',{name:'Offline HTML',exact:true}),page.getByRole('button',{name:/Share PDF|Save to share/}).first()],page.getByRole('dialog'));
 await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();
 await page.getByRole('button',{name:'Account and training',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Create account',exact:true}).click();
 await dialog.getByLabel('Name',{exact:true}).fill('Alex');await dialog.getByLabel('Email',{exact:true}).fill('walkthrough@example.com');await dialog.getByLabel('Password',{exact:true}).fill('isolated-walkthrough-passphrase-2026');
 await shot('account',[dialog.getByRole('button',{name:'Create my account',exact:true})],dialog);
 await dialog.getByRole('button',{name:'Create my account',exact:true}).click();await expect(dialog.getByRole('button',{name:'Save current result',exact:true})).toBeEnabled();
 await shot('save',[dialog.getByRole('button',{name:'Save current result',exact:true})],dialog);
 await dialog.getByRole('button',{name:'Save current result',exact:true}).click();await expect(dialog.getByRole('button',{name:'View result',exact:true})).toBeVisible();await dialog.getByRole('button',{name:'View result',exact:true}).click();
 await page.waitForTimeout(600);await shot('saved',[dialog.getByRole('button',{name:'Close result',exact:true})],dialog);
 await fs.writeFile(path.join(project,'capture-meta.json'),JSON.stringify({captured_at:new Date().toISOString(),captures,errors,fixture_calls:fixtureCalls,paid_visual_calls:0,in_memory_accounts:true,notes:'Screens are the actual local app. The extraction fixture maps the supplied four-step Parts_Sorting.txt literally; no camera, microphone, paid vision, or share upload was invoked. Manual confirmation, bookmarks, exception, PDF preparation and account save are actual interactions.'},null,2));
}finally{await browser.close();await app.close();accounts.close();}
